#!/usr/bin/bash

# First argument is the option you choose(build, run, debug, test), note: all option will build first
# Second arugment can override ASSIGNMENT
# Third arugment can override ASSIGNMENT_NUM
# Fourth argument can override I3_WORKSPACE_NUM

ASSIGNMENT=ASST0
ASSIGNMENT=${2:-$ASSIGNMENT}
ASSIGNMENT_NUM=${ASSIGNMENT: -1}
ASSIGNMENT_NUM=${3:-$ASSIGNMENT_NUM}
I3_WORKSPACE_NUM=10
I3_WORKSPACE_NUM=${4:-$I3_WORKSPACE_NUM}

BUILD_CMD="cd ~/ece344/os161/kern/conf && ./config $ASSIGNMENT && cd ~/ece344/os161/kern/compile/$ASSIGNMENT && make depend && make && make install"
RUN_CMD="cd ~/ece344/root && sys161 kernel ; bash"
RUN_WITH_DEBUG_CMD="cd ~/ece344/root && sys161 -w kernel ; bash"
GDB_CMD="\"target\ remote\ unix:.sockets/gdb\""
DEBUG_CMD="echo $GDB_CMD >> ~/.gdbinit && cd ~/ece344/root && cs161-gdb kernel"
TEST_CMD="cd ~/ece344/root && export PATH=\"\\\$HOME/ece344/tester/bin:\\\$PATH\" && os161-tester $ASSIGNMENT_NUM"

build() {
    i3-msg workspace $I3_WORKSPACE_NUM
    gnome-terminal -- bash -c "docker run --name ece344 --volume "$(pwd):/root/ece344" -it --rm tech4me/ece344:latest bash -c \"$BUILD_CMD ; bash\""
}

build_run() {
    i3-msg workspace $I3_WORKSPACE_NUM
    gnome-terminal -- bash -c "docker run --name ece344 --volume "$(pwd):/root/ece344" -it --rm tech4me/ece344:latest bash -c \"$BUILD_CMD && $RUN_CMD\""
}

build_debug() {
    i3-msg workspace $I3_WORKSPACE_NUM
    gnome-terminal -- bash -c "docker run --name ece344 --volume "$(pwd):/root/ece344" -it --rm tech4me/ece344:latest bash -c \"$BUILD_CMD && $RUN_WITH_DEBUG_CMD\""
    sleep 1 # Wait for docker and gdb to load up
    gnome-terminal -- bash -c "docker exec -it ece344 bash -c \"$DEBUG_CMD\""
}

build_test() {
    i3-msg workspace $I3_WORKSPACE_NUM
    gnome-terminal -- bash -c "docker run --name ece344 --volume "$(pwd):/root/ece344" -it --rm tech4me/ece344:latest bash -c \"$BUILD_CMD && $TEST_CMD ; bash\""
}

case $1 in
build)
    build
    ;;
run)
    build_run
    ;;
debug)
    build_debug
    ;;
test)
    build_test
    ;;
*)
    echo "Usage: $0 {build, run, debug, test}"
    exit 1
esac
